#!/bin/bash

D=$(dirname $(readlink -f ${BASH_SOURCE}))
source "$D/setup_env.sh"

cd $ROOT

echo "Doing overlay..."

cp -v $ROOT/overlay/adbd $RAMDISK_OUT/sbin/adbd
cp -v $ROOT/overlay/default.prop $RAMDISK_OUT/

cp -v $ROOT/logo/logo.rle $RAMDISK_OUT/logo.rle
