#!/bin/bash

D=$(dirname $(readlink -f ${BASH_SOURCE}))
source "$D/setup_env.sh"

usage() {
cat << EOF
usage: $0 [<OPTIONS>]

Generates iperf test results, designed to run on any TWO Xperia Z devices
connected to the computer.

OPTIONS:
   -h   Show this message.
   -r   Skip reboot
EOF
}

NO_REBOOT=

# parse the incoming parameters
while getopts "hr" options; do
    case $options in
        h) usage; exit 0;;
        r) NO_REBOOT=1 ;;
        *) usage; exit 1;;
    esac
done

run_iperf() {

    local ghz=$1

    local serials=$(adbs shell getprop ro.serialno)

    local serial1=$(echo $serials | cut -d' ' -f1)
    local serial2=$(echo $serials | cut -d' ' -f2)

    local ip1=$(gen_ip $serial1)
    local ip2=$(gen_ip $serial2)

    echo "Starting server on $serial1/$ip1"
    adbpath=`which adb`

    log1="/tmp/iperf_server_$serial1.$ghz.log"
    xterm -e "sh -c \"$adbpath -s $serial1 shell iperf -s -i 1 -u | tee $log1\"" &

    echo "Starting client on $serial2/$ip2"

    log2="/tmp/iperf_client_$serial2.$ghz.log"
    xterm -e "sh -c \"$adbpath -s $serial2 shell iperf -c $ip1 -i 1 -t 10 -u -b 100M | tee $log2\""

    # Twice to make sure iperf quits!
    adb -s $serial1 shell /system/xbin/killall iperf
    adb -s $serial1 shell /system/xbin/killall iperf

    cat $log1 $log2
}

echo "Changing to 5 GHz, channel 36, HT20"

if [[ -z $NO_REBOOT ]]; then
    reboot_phones
fi

adbs_p root
sleep_countdown 2 "Waiting for remote adb to restart as root"

all_join_mesh 36 HT20
run_iperf HT20_5GHz

echo "Changing to 5 GHz, channel 36, legacy"

reboot_phones
all_join_mesh 36
run_iperf legacy_5GHz

echo "Changing to 2.4 GHz, channel 11, HT20"

reboot_phones
all_join_mesh 11 HT20
run_iperf HT20_2.4GHz

echo "Changing to 2.4 GHz, channel 11, legacy"

reboot_phones
all_join_mesh 11
run_iperf legacy_2.4GHz
