#!/bin/bash

D=$(dirname $(readlink -f ${BASH_SOURCE}))
source "$D/setup_env.sh"

usage() {
cat << EOF
usage: $0 [<OPTIONS>]

Runs a ping test between ALL Xperia Z devices connected to the computer.

OPTIONS:
   -h   Show this message.
EOF
}

# parse the incoming parameters
while getopts "h" options; do
    case $options in
        h ) usage; exit 0;;
        * ) usage; exit 1;;
    esac
done

reboot_phones
join_mesh 36 HT20

logs=`tempfile -p r_p_`
add_on_exit "rm $logs"

for serial in `list_xperiaz`; do
    for other_serial in `list_xperiaz`; do
        if [[ $serial == $other_serial ]]; then
            continue
        fi
        ip=$(gen_ip $other_serial)
        log="/tmp/ping_from_${serial}_to_${other_serial}.log"
        add_on_exit "rm $log"
        echo $log >>$logs
        xterm -e "sh -c \"adb -s $serial shell ping $ip | tee $log\"" &
        sleep 0.5
    done
done

sleep_countdown 20 "Waiting for some data from ping"

for log in `cat $logs`; do
    echo '<<<<<< ' $log ' >>>>>>'
    cat $log
done

adbs shell killall ping
